---
name: Terraform Module
on:
  push:
  workflow_dispatch:

jobs:
  publish-module:
    uses: taskrabbit/github_workflows/.github/workflows/terraform-module.yaml@main
    with:
      namespace: taskrabbit
      system: aws
      name: "openvpn" # This is required to be updated by the downstream repository.
